// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"saui/locale"
	"saui/templates/layout"
)

func BlogPostCRAClock(csrfToken string, lang locale.Lang) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"blog-post-hero\"><div class=\"blog-post-hero__image\"><img src=\"/static/img/blog-cra-clock.svg\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"Three concentric arcs sweeping from a single point marked Discovery: a quarter turn for the 24-hour early warning, three quarters for the 72-hour notification, and a full turn for the 14-day final report, above a timeline running from the Cyber Resilience Act entering into force in December 2024 to full obligations in December 2027.",
				"Tres arcos concéntricos que parten de un único punto marcado como Descubrimiento: un cuarto de vuelta para la alerta temprana de 24 horas, tres cuartos para la notificación de 72 horas y una vuelta completa para el informe final de 14 días, sobre una línea temporal que va desde la entrada en vigor de la Ley de Ciberresiliencia en diciembre de 2024 hasta las obligaciones plenas en diciembre de 2027.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 27, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" loading=\"eager\" decoding=\"async\" width=\"1600\" height=\"900\"></div><div class=\"blog-post-hero__header\"><nav class=\"page-hero__breadcrumb\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Breadcrumb", "Ruta de navegación"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 35, Col: 95}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 templ.SafeURL
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(lang.Prefix() + "/blog"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 36, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Blog</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(` / Post`, ` / Publicación`))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 36, Col: 98}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</nav><h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("The clock starts at discovery", "El reloj empieza en el descubrimiento"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 38, Col: 90}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h1><p class=\"lead\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"From 11 September 2026 the Cyber Resilience Act's reporting obligations are enforceable. A manufacturer who learns that a vulnerability in a shipped product is being exploited has 24 hours to say so. Writing the notice takes an afternoon. Knowing what happened, and to whom, is the part your architecture decided long before the clock started.",
				"Desde el 11 de septiembre de 2026 son exigibles las obligaciones de notificación de la Ley de Ciberresiliencia. Un fabricante que descubre que una vulnerabilidad de un producto ya distribuido está siendo explotada dispone de 24 horas para comunicarlo. Redactar el aviso lleva una tarde. Saber qué ocurrió y a quién es la parte que tu arquitectura decidió mucho antes de que el reloj empezara a correr.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 42, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p><time class=\"blog-post-hero__date\" datetime=\"2026-09-10\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("10 September 2026", "10 de septiembre de 2026"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 43, Col: 118}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</time></div></div><article class=\"blog-post\"><section><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Regulation (EU) 2024/2847 — the Cyber Resilience Act — entered into force on
					10 December 2024, and most of the industry filed it under "2027 problem". That
					filing was half right. The bulk of the essential requirements, the conformity
					assessment, and the CE marking do apply from 11 December 2027. But the reporting
					obligations in Article 14 were pulled forward deliberately, and they have applied
					since 11 September 2026.`,
				`El Reglamento (UE) 2024/2847 —la Ley de Ciberresiliencia— entró en vigor el
					10 de diciembre de 2024, y buena parte del sector lo archivó como un "problema de
					2027". Ese archivo era correcto a medias. El grueso de los requisitos esenciales,
					la evaluación de la conformidad y el marcado CE se aplican, en efecto, desde el
					11 de diciembre de 2027. Pero las obligaciones de notificación del artículo 14 se
					adelantaron de forma deliberada y se aplican desde el 11 de septiembre de 2026.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 61, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The rest of the regulation improves products that have not been built yet.
					Article 14 is about products already in the field, being attacked today, whose
					users have no way of learning that they are exposed. Waiting three years to tell
					those users was indefensible.`,
				`El resto del reglamento mejora productos que aún no se han construido. El
					artículo 14 trata de productos ya desplegados, atacados hoy, cuyos usuarios no
					tienen forma de saber que están expuestos. Esperar tres años para avisar a esos
					usuarios era indefendible.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 71, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("First: does it apply to you?", "Primero: ¿te aplica?"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 74, Col: 73}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The Cyber Resilience Act regulates products with digital elements placed on the
					EU market. Software you distribute is a product, and so are firmware and a
					connected device. A website is not, and neither is a software-as-a-service
					application in the ordinary case: services are governed by NIS2, not by the CRA.
					If your entire delivery model is a URL your customers visit, Article 14 does not
					reach you directly.`,
				`La Ley de Ciberresiliencia regula los productos con elementos digitales
					introducidos en el mercado de la UE. El software que distribuyes es un producto,
					y también lo son el firmware y un dispositivo conectado. Un sitio web no lo es, y
					tampoco lo es una aplicación de software como servicio en el caso ordinario: los
					servicios se rigen por NIS2, no por la CRA. Si todo tu modelo de entrega es una
					URL que tus clientes visitan, el artículo 14 no te alcanza directamente.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 88, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`There are two ways that comfortable conclusion stops being true. The first is the
					remote data processing solution: where a hosted backend is necessary for a
					distributed product to perform its function, that backend is pulled into the
					product's scope. Ship a desktop client, a mobile app, or a device that will not
					work without your API, and your API is in scope with it. The second is being
					somebody else's dependency. A component integrated into a manufacturer's product
					is itself a product with digital elements, so a library, an SDK, or a self-hosted
					server distributed to customers carries the obligation regardless of how the
					vendor thinks of itself.`,
				`Hay dos formas en que esa conclusión cómoda deja de ser cierta. La primera es la
					solución de tratamiento de datos a distancia: cuando un backend alojado es
					necesario para que un producto distribuido cumpla su función, ese backend queda
					dentro del alcance del producto. Si distribuyes un cliente de escritorio, una
					aplicación móvil o un dispositivo que no funciona sin tu API, tu API entra en el
					alcance con él. La segunda es ser la dependencia de otro. Un componente integrado
					en el producto de un fabricante es a su vez un producto con elementos digitales,
					de modo que una biblioteca, un SDK o un servidor autoalojado que se distribuye a
					clientes conlleva la obligación, con independencia de cómo se conciba el proveedor
					a sí mismo.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 109, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Free and open-source software developed outside commercial activity is excluded.
					Products already covered by sector regimes — medical devices, motor vehicles,
					civil aviation — stay under those regimes. Everything else that ships as software
					should assume it is in scope until someone has checked properly.`,
				`El software libre y de código abierto desarrollado fuera de una actividad
					comercial queda excluido. Los productos ya cubiertos por regímenes sectoriales
					—productos sanitarios, vehículos de motor, aviación civil— permanecen bajo esos
					regímenes. Todo lo demás que se distribuya como software debería asumir que está
					dentro del alcance hasta que alguien lo haya comprobado en serio.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 120, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</p><blockquote class=\"callout\"><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`If you are a pure web application, Article 14 is not your obligation — but the
						question it asks is still your problem. NIS2 puts essential and important
						entities on the same 24-hour and 72-hour clock for significant incidents. The
						legal instrument differs. The engineering problem is identical.`,
				`Si eres una aplicación web pura, el artículo 14 no es tu obligación, pero la
						pregunta que plantea sigue siendo tu problema. NIS2 somete a las entidades
						esenciales e importantes al mismo reloj de 24 y 72 horas para los incidentes
						significativos. El instrumento jurídico es distinto. El problema de ingeniería
						es idéntico.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 132, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</p></blockquote></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var17 string
			templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("The three deadlines", "Los tres plazos"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 136, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var18 string
			templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Article 14 defines two reporting tracks, each with three stages. One is triggered
					by a vulnerability in your product that is under active exploitation, rather than
					merely disclosed. The other is triggered by a severe incident affecting the
					security of the product. Both are reported through a single EU reporting platform
					to the CSIRT designated as coordinator and to ENISA. The stages below are the
					vulnerability track; the incident track runs to the same first two deadlines.`,
				`El artículo 14 define dos vías de notificación, cada una con tres fases. Una se
					activa por una vulnerabilidad de tu producto que está siendo explotada
					activamente, y no solamente divulgada. La otra se activa por un incidente grave
					que afecte a la seguridad del producto. Ambas se notifican a través de una única
					plataforma de notificación de la UE al CSIRT designado como coordinador y a
					ENISA. Las fases que siguen son las de la vía de vulnerabilidades; la vía de
					incidentes comparte los dos primeros plazos.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 151, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</p><dl class=\"incident-log\"><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var19 string
			templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Within 24 hours — the early warning", "En 24 horas — la alerta temprana"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 153, Col: 96}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var20 string
			templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`A short notice that you are aware of an actively exploited vulnerability, and
						whether you know the Member States in which the product has been made
						available. It is deliberately small, because speed is the whole point of it.
						Nobody expects root cause analysis on the first day.`,
				`Un aviso breve de que tienes conocimiento de una vulnerabilidad explotada
						activamente, e indicando si conoces los Estados miembros en los que se ha
						comercializado el producto. Es deliberadamente escueto, porque la rapidez es
						todo su propósito. Nadie espera un análisis de causa raíz el primer día.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 163, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var21 string
			templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Within 72 hours — the notification", "En 72 horas — la notificación"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 164, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var22 string
			templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`General information about the product and the vulnerability, the nature of the
						exploitation, and any corrective or mitigating measure taken or that users can
						take. This is where the question becomes technical: describing the nature of
						the exploitation means reconstructing what the attacker did, from whatever
						records you were already keeping.`,
				`Información general sobre el producto y la vulnerabilidad, la naturaleza de la
						explotación y cualquier medida correctora o mitigadora adoptada o que los
						usuarios puedan adoptar. Aquí la cuestión se vuelve técnica: describir la
						naturaleza de la explotación significa reconstruir lo que el atacante hizo, a
						partir de los registros que ya estuvieras guardando.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 176, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var23 string
			templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Within 14 days — the final report", "En 14 días — el informe final"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 177, Col: 92}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var24 string
			templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Due once a corrective or mitigating measure is available. It carries a
						description of the vulnerability including its severity and impact,
						information on any malicious actor identified, and the details of the fix. For
						severe incidents the equivalent final report is due within one month of the
						notification.`,
				`Debido una vez que existe una medida correctora o mitigadora. Contiene una
						descripción de la vulnerabilidad, incluidas su gravedad y su impacto,
						información sobre cualquier actor malicioso identificado y los detalles de la
						corrección. Para los incidentes graves, el informe final equivalente vence en
						el plazo de un mes desde la notificación.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 189, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</dd></dl><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var25 string
			templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Separately, and running alongside all of the above, the manufacturer must inform
					the affected users about the vulnerability and, where appropriate, about the
					corrective measures they should apply. Notifying the regulator does not discharge
					the duty to your customers.`,
				`Al margen de todo lo anterior, y en paralelo, el fabricante debe informar a los
					usuarios afectados sobre la vulnerabilidad y, cuando proceda, sobre las medidas
					correctoras que deban aplicar. Notificar al regulador no libera del deber hacia
					tus clientes.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 200, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var26 string
			templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Discovery, not triage", "Descubrimiento, no clasificación"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 203, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var26))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var27 string
			templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The single most expensive misreading of Article 14 is about when the 24 hours
					begin. They begin when the manufacturer becomes aware of the active exploitation,
					which is earlier than every internal milestone you might mistake for the start:
					the security team's confirmation, a reproduction on a test system, the formal
					opening of an incident. Awareness is the trigger, and awareness includes the
					support ticket nobody escalated and the researcher email that sat in a shared
					inbox over a weekend.`,
				`La lectura errónea más cara del artículo 14 tiene que ver con cuándo empiezan las
					24 horas. Empiezan cuando el fabricante tiene conocimiento de la explotación
					activa, un momento anterior a todos los hitos internos que podrías confundir con
					el inicio: la confirmación del equipo de seguridad, la reproducción en un sistema
					de pruebas, la apertura formal del incidente. El desencadenante es el
					conocimiento, y ese conocimiento incluye el ticket de soporte que nadie escaló y
					el correo del investigador que pasó un fin de semana en un buzón compartido.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 219, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var27))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var28 string
			templ_7745c5c3_Var28, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`This has a mundane consequence that matters more than most of the regulation:
					your intake path is part of your compliance posture. A published, monitored
					reporting channel with a stated acknowledgement window earns its place here: it
					puts a timestamp on "when did you become aware?", which is otherwise a matter of
					argument.`,
				`Esto tiene una consecuencia mundana que importa más que buena parte del
					reglamento: tu vía de entrada forma parte de tu postura de cumplimiento. Un canal
					de notificación publicado y vigilado, con una ventana de acuse de recibo
					declarada, se gana aquí su sitio: pone una marca de tiempo a "¿cuándo tuviste
					conocimiento?", que de otro modo queda a merced de la discusión.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 231, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var28))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var29 string
			templ_7745c5c3_Var29, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Why this is an architecture question", "Por qué esto es una cuestión de arquitectura"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 234, Col: 106}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var29))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var30 string
			templ_7745c5c3_Var30, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Twenty-four hours is enough time to write a paragraph, and far too little to
					build an evidence pipeline. Whatever you can say at hour 23 is whatever your
					system was already recording at hour zero, and the shape of that recording is
					decided by where state lives.`,
				`Veinticuatro horas bastan para escribir un párrafo, y son muy pocas para
					construir una cadena de evidencias. Lo que puedas afirmar en la hora 23 será lo
					que tu sistema ya estuviera registrando en la hora cero, y la forma de ese
					registro la decide dónde reside el estado.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 244, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var30))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var31 string
			templ_7745c5c3_Var31, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The 72-hour notification asks three things: what the vulnerability is, how it
					was exploited, and who was affected. In an architecture where the client
					holds state and the server accepts whatever the client asserts, those questions
					are answered from logs of the requests that arrived — which record the assertions,
					not the reasoning behind them. A tampered client sends a well-formed request. The
					log shows a well-formed request. Reconstructing intent from that means inference,
					and inference is slow.`,
				`La notificación de 72 horas pide tres cosas: qué es la vulnerabilidad, cómo se
					explotó y a quién afectó. En una arquitectura donde el
					cliente mantiene el estado y el servidor acepta lo que el cliente afirma, esas
					preguntas se responden desde los registros de las solicitudes que llegaron, que
					registran las afirmaciones, no el razonamiento que hay detrás. Un cliente
					manipulado envía una solicitud bien formada. El registro muestra una solicitud
					bien formada. Reconstruir la intención a partir de eso exige inferir, e inferir es
					lento.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 261, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var31))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var32 string
			templ_7745c5c3_Var32, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`In a server-authoritative system the same questions are queries. Every change to
					application state passes through the server, is validated there, and is appended
					to one log before it takes effect. That makes the audit trail the storage model
					rather than a feature somebody remembered to add, and it turns "which sessions
					performed this action, in this window" into a WHERE clause over a table that
					already exists.`,
				`En un sistema autorizado por el servidor, esas mismas preguntas son consultas.
					Todo cambio del estado de la aplicación pasa por el servidor, se valida allí y se
					añade a un único registro antes de surtir efecto. Eso convierte el rastro de
					auditoría en el modelo de almacenamiento, y no en una funcionalidad que alguien
					se acordó de añadir, y convierte "qué sesiones realizaron esta acción, en esta
					ventana" en una cláusula WHERE sobre una tabla que ya existe.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 275, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var32))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "</p><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var33 string
			templ_7745c5c3_Var33, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`-- Hour 2 of the 24: the blast radius, as a query.
SELECT session_id, type, occurred_at
FROM   events
WHERE  type = ?
AND    occurred_at BETWEEN ? AND ?
ORDER  BY occurred_at;`,
				`-- Hora 2 de las 24: el radio de impacto, como consulta.
SELECT session_id, type, occurred_at
FROM   events
WHERE  type = ?
AND    occurred_at BETWEEN ? AND ?
ORDER  BY occurred_at;`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 289, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var33))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</code></pre><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var34 string
			templ_7745c5c3_Var34, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`That is this site's own event table, unchanged. It is what an append-only
					server-owned log makes available by default. The 14-day final report asks for
					severity and impact; impact is a count over the same table.`,
				`Esa es la propia tabla de eventos de este sitio, sin cambios. Es lo que un
					registro de solo anexado, propiedad del servidor, ofrece por defecto. El informe
					final de 14 días pide gravedad e impacto; el impacto es un recuento sobre esa
					misma tabla.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 298, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var34))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var35 string
			templ_7745c5c3_Var35, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The second architectural dividend is narrower but shows up in the same window:
					the size of the thing you must reason about. A product with no client-held state
					and two direct dependencies has a defect surface one engineer can hold in their
					head. Determining whether a disclosed vulnerability is reachable from your code
					is the first question of the 24 hours, and it is answerable in minutes with a
					dependency graph of ten modules and a call-graph scanner. It is a multi-day
					exercise across a thousand transitive packages.`,
				`El segundo dividendo arquitectónico es más limitado, pero aparece en la misma
					ventana: el tamaño de aquello sobre lo que debes razonar. Un producto sin estado
					en el cliente y con dos dependencias directas tiene una superficie de defectos que
					una sola persona puede abarcar mentalmente. Determinar si una vulnerabilidad
					divulgada es alcanzable desde tu código es la primera pregunta de las 24 horas, y
					se responde en minutos con un grafo de dependencias de diez módulos y un
					analizador del grafo de llamadas. Es un ejercicio de varios días a lo largo de mil
					paquetes transitivos.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 315, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var35))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var36 string
			templ_7745c5c3_Var36, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Both of those are available before the clock starts, or they are not available
					at all. A property you want under pressure has to be a structural fact, because
					there is no time to acquire one once the pressure arrives.`,
				`Ambos están disponibles antes de que el reloj empiece a correr, o no lo están en
					absoluto. Una propiedad que quieres tener bajo presión debe ser un hecho
					estructural, porque no hay tiempo de adquirirla una vez que la presión llega.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 323, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var36))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var37 string
			templ_7745c5c3_Var37, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("What the architecture does not do", "Lo que la arquitectura no hace"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 326, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var37))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var38 string
			templ_7745c5c3_Var38, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`It does not decide that a vulnerability is being actively exploited. That is a
					judgement made by people, from evidence, and getting it wrong in either direction
					is costly: notify everything and the signal is worthless, notify nothing and the
					24 hours expired days ago. No storage model makes that call.`,
				`No decide que una vulnerabilidad esté siendo explotada activamente. Ese es un
					juicio que hacen personas, a partir de evidencias, y equivocarse en cualquiera de
					las dos direcciones sale caro: notificarlo todo y la señal no vale nada, no
					notificar nada y el plazo de 24 horas expiró hace días. Ningún modelo de
					almacenamiento decide eso.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 337, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var38))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var39 string
			templ_7745c5c3_Var39, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`It does not file the notification, maintain the software bill of materials the
					regulation requires, run the conformity assessment, or affix the CE marking. It
					does not give you a coordinated disclosure policy, a support period, or a
					vulnerability handling process — all of which Annex I Part II requires, all of
					which are documents and habits rather than code. It does not retain logs for you:
					an append-only table you truncate quarterly answers nothing about an intrusion
					discovered in month five.`,
				`No presenta la notificación, no mantiene la lista de materiales de software que
					exige el reglamento, no realiza la evaluación de la conformidad ni coloca el
					marcado CE. No te proporciona una política de divulgación coordinada, un período
					de soporte ni un proceso de gestión de vulnerabilidades, todo lo cual exige la
					parte II del anexo I y todo lo cual son documentos y hábitos antes que código. No
					conserva los registros por ti: una tabla de solo anexado que truncas cada
					trimestre no responde nada sobre una intrusión descubierta en el quinto mes.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 353, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var39))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var40 string
			templ_7745c5c3_Var40, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`What it does is remove the worst failure mode from the list of things that can
					happen to you on the first day: discovering that the answer does not exist. The
					deadline is short enough that querying a fact and reconstructing one land on
					opposite sides of the obligation. Where state lives decides which of the two you
					will be doing.`,
				`Lo que sí hace es eliminar el peor modo de fallo de la lista de cosas que pueden
					ocurrirte el primer día: descubrir que la respuesta no existe. El plazo es lo
					bastante breve como para que consultar un hecho y reconstruirlo caigan a lados
					opuestos de la obligación. Dónde reside el estado decide cuál de las dos cosas
					estarás haciendo.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 365, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var40))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var41 string
			templ_7745c5c3_Var41, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Penalties for breaching the essential requirements reach €15 million or 2.5% of
					worldwide annual turnover, which is the figure that gets the regulation read at
					all. The 24 hours is the part that sends people to look at their own logs, and
					that is the harder thing to arrange after the fact.`,
				`Las sanciones por incumplir los requisitos esenciales alcanzan los 15 millones de
					euros o el 2,5 % de la facturación anual mundial, que es la cifra que consigue
					que el reglamento se lea siquiera. Las 24 horas son la parte que lleva a la gente
					a mirar sus propios registros, y eso es lo más difícil de organizar a posteriori.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 375, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var41))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "</p><p><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var42 templ.SafeURL
			templ_7745c5c3_Var42, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(lang.Prefix() + "/blog/eu-compliance"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 376, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var42))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var43 string
			templ_7745c5c3_Var43, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("How the wider EU regime maps onto architecture", "Cómo se relaciona el régimen europeo más amplio con la arquitectura"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_cra_clock.templ`, Line: 376, Col: 200}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var43))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "</a></p></section></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(
			lang.T("The clock starts at discovery", "El reloj empieza en el descubrimiento"),
			lang.T(
				"From 11 September 2026 the Cyber Resilience Act gives manufacturers 24 hours to warn ENISA about an actively exploited vulnerability. Meeting that deadline is a question about where your application's state lives.",
				"Desde el 11 de septiembre de 2026, la Ley de Ciberresiliencia concede a los fabricantes 24 horas para alertar a ENISA sobre una vulnerabilidad explotada activamente. Cumplir ese plazo es una cuestión sobre dónde reside el estado de tu aplicación.",
			),
			csrfToken,
			lang.Prefix()+"/blog/cra-clock",
			"/static/css/blog.css",
			lang,
		).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
