// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"saui/locale"
	"saui/templates/layout"
)

func BlogPostEUCompliance(csrfToken string, lang locale.Lang) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"blog-post-hero\"><div class=\"blog-post-hero__image\"><img src=\"/static/img/blog-eu-compliance.svg\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"A ring of twelve EU stars orbiting a central shield representing server-owned, logged, and mediated application state, surrounded by callouts for GDPR Articles 25 and 32, the NIS2 Directive, the Cyber Resilience Act, DORA, and OWASP.",
				"Un anillo de doce estrellas de la UE que orbita un escudo central que representa el estado de la aplicación propiedad del servidor, registrado y mediado, rodeado de referencias a los artículos 25 y 32 del RGPD, la Directiva NIS2, la Ley de Ciberresiliencia, DORA y OWASP.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 27, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" loading=\"eager\" decoding=\"async\" width=\"1600\" height=\"900\"></div><div class=\"blog-post-hero__header\"><nav class=\"page-hero__breadcrumb\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Breadcrumb", "Ruta de navegación"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 35, Col: 95}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 templ.SafeURL
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(lang.Prefix() + "/blog"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 36, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Blog</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(` / Post`, ` / Publicación`))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 36, Col: 98}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</nav><h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Compliance by architecture: GDPR, NIS2, and the EU security baseline", "Cumplimiento por arquitectura: RGPD, NIS2 y el estándar de seguridad de la UE"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 38, Col: 170}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h1><p class=\"lead\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"European regulation no longer asks whether an application is secure — it asks you to prove it, by design and by default. Most teams answer with policy documents. A server-authoritative architecture lets several of those answers be structural facts about the system instead.",
				"La regulación europea ya no pregunta si una aplicación es segura: te pide demostrarlo, desde el diseño y por defecto. La mayoría de los equipos responden con documentos de políticas. Una arquitectura autorizada por el servidor permite que varias de esas respuestas sean hechos estructurales del sistema.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 42, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p><time class=\"blog-post-hero__date\" datetime=\"2026-07-24\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("24 July 2026", "24 de julio de 2026"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 43, Col: 108}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</time></div></div><article class=\"blog-post\"><section><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`For most of the web's history, application security in the European Union was
					governed by a single regulation with teeth — the GDPR — and a scattering of
					sector rules. That is no longer the situation. Between 2024 and 2027 the EU
					has assembled a layered cybersecurity regime that reaches almost every
					organisation running a web application for European users: the NIS2 Directive,
					the Cyber Resilience Act, and, for the financial sector, DORA. Each of them
					carries administrative fines, and several carry personal liability for management.`,
				`Durante casi toda la historia de la web, la seguridad de las aplicaciones en la
					Unión Europea se regía por un único reglamento con dientes —el RGPD— y un puñado
					de normas sectoriales. Esa ya no es la situación. Entre 2024 y 2027, la UE ha
					construido un régimen de ciberseguridad por capas que alcanza a casi cualquier
					organización que opere una aplicación web para usuarios europeos: la Directiva
					NIS2, la Ley de Ciberresiliencia y, para el sector financiero, DORA. Todas
					conllevan multas administrativas, y varias implican responsabilidad personal
					para la dirección.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 64, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The common thread across all of them is a shift in burden. The regulator no longer
					accepts "we take security seriously" as a statement of intent. It expects
					security to be demonstrable — built in from the design stage, on by default,
					evidenced by records, and testable. Architecture is no longer an implementation
					detail below the compliance line. It is where a growing share of the compliance
					obligation is actually met, or not.`,
				`El hilo común de todas ellas es un cambio en la carga de la prueba. El regulador
					ya no acepta "nos tomamos la seguridad en serio" como declaración de intenciones.
					Espera que la seguridad sea demostrable: incorporada desde la fase de diseño,
					activada por defecto, evidenciada mediante registros y verificable. La
					arquitectura ha dejado de ser un detalle de implementación por debajo de la
					línea de cumplimiento. Es donde se satisface —o no— una parte creciente de la
					obligación de cumplir.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 79, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"This post maps the requirements a European web application faces onto the properties of a server-authoritative architecture — being precise about what the architecture gives you for free, and honest about what it does not.",
				"Esta publicación relaciona los requisitos que enfrenta una aplicación web europea con las propiedades de una arquitectura autorizada por el servidor, siendo preciso sobre lo que la arquitectura ofrece de forma gratuita y honesto sobre lo que no.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 83, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("The regulations that touch a web application", "Las regulaciones que afectan a una aplicación web"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 86, Col: 118}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</h2><dl class=\"incident-log\"><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("GDPR — Regulation (EU) 2016/679", "RGPD — Reglamento (UE) 2016/679"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 88, Col: 91}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`In force since 2018. Article 5 sets the processing principles — data minimisation,
						storage limitation, integrity and confidentiality, and accountability. Article 25
						requires data protection by design and by default. Article 32 requires security
						of processing appropriate to the risk. Article 30 requires records of processing
						activities. Fines reach €20 million or 4% of global annual turnover.`,
				`En vigor desde 2018. El artículo 5 establece los principios de tratamiento
						—minimización de datos, limitación del plazo de conservación, integridad y
						confidencialidad, y responsabilidad proactiva—. El artículo 25 exige la
						protección de datos desde el diseño y por defecto. El artículo 32 exige una
						seguridad del tratamiento adecuada al riesgo. El artículo 30 exige registros
						de las actividades de tratamiento. Las multas alcanzan los 20 millones de euros
						o el 4 % de la facturación anual global.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 102, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("NIS2 — Directive (EU) 2022/2555", "NIS2 — Directiva (UE) 2022/2555"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 103, Col: 91}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var17 string
			templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`National transposition due October 2024. It obliges essential and important
						entities across many sectors to adopt cybersecurity risk-management measures
						(Article 21) and to report significant incidents on a strict clock — an early
						warning within 24 hours, a full notification within 72. Management bodies are
						accountable and can be held personally liable for non-compliance.`,
				`Transposición nacional prevista para octubre de 2024. Obliga a las entidades
						esenciales e importantes de numerosos sectores a adoptar medidas de gestión de
						riesgos de ciberseguridad (artículo 21) y a notificar los incidentes
						significativos con plazos estrictos: una alerta temprana en 24 horas y una
						notificación completa en 72. Los órganos de dirección son responsables y pueden
						responder personalmente por el incumplimiento.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 116, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var18 string
			templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Cyber Resilience Act — Regulation (EU) 2024/2847", "Ley de Ciberresiliencia — Reglamento (UE) 2024/2847"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 117, Col: 128}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var19 string
			templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Entered into force in December 2024, with the main obligations applying from 2027.
						It imposes essential cybersecurity requirements on products with digital elements:
						secure by design and by default, delivered without known exploitable
						vulnerabilities, with an attack surface kept to a minimum and a documented
						vulnerability-handling process across the product lifecycle.`,
				`Entró en vigor en diciembre de 2024, con las obligaciones principales aplicables
						a partir de 2027. Impone requisitos esenciales de ciberseguridad a los productos
						con elementos digitales: seguros desde el diseño y por defecto, entregados sin
						vulnerabilidades explotables conocidas, con una superficie de ataque reducida al
						mínimo y un proceso documentado de gestión de vulnerabilidades a lo largo del
						ciclo de vida del producto.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 130, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var20 string
			templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("DORA — Regulation (EU) 2022/2554", "DORA — Reglamento (UE) 2022/2554"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 131, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var21 string
			templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Applies to financial entities from January 2025. It requires ICT risk management,
						resilience testing, and detailed incident classification and reporting, with an
						explicit expectation of traceability across systems — the ability to reconstruct
						what happened, when, and to which data.`,
				`Aplicable a las entidades financieras desde enero de 2025. Exige gestión de
						riesgos de las TIC, pruebas de resiliencia y una clasificación y notificación
						detallada de incidentes, con una expectativa explícita de trazabilidad entre
						sistemas: la capacidad de reconstruir qué ocurrió, cuándo y sobre qué datos.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 141, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</dd><dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var22 string
			templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("ePrivacy — Directive 2002/58/EC", "Privacidad electrónica — Directiva 2002/58/CE"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 142, Col: 106}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</dt><dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var23 string
			templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Still the governing rule for cookies and client-side storage. Reading from or
						writing to a user's device — cookies, localStorage, fingerprinting — requires
						prior informed consent unless strictly necessary to provide the service the
						user requested.`,
				`Sigue siendo la norma que rige las cookies y el almacenamiento en el cliente.
						Leer o escribir en el dispositivo de un usuario —cookies, localStorage,
						fingerprinting— requiere consentimiento informado previo, salvo que sea
						estrictamente necesario para prestar el servicio que el usuario solicitó.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 152, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</dd></dl><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var24 string
			templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"None of these regulations names an architecture. All of them describe properties. The question worth asking is which architecture makes those properties the default rather than an ongoing effort.",
				"Ninguna de estas regulaciones nombra una arquitectura. Todas describen propiedades. La pregunta que merece la pena hacerse es qué arquitectura convierte esas propiedades en el comportamiento por defecto, y no en un esfuerzo continuo.",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 157, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var25 string
			templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Data protection by design — GDPR Article 25", "Protección de datos desde el diseño — RGPD artículo 25"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 160, Col: 128}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var26 string
			templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Article 25 is the clause that most directly rewards architectural decisions. It
					requires that data protection is engineered into the system from the outset and
					that, by default, only the personal data necessary for each specific purpose is
					processed. It is the one requirement that a diligent policy cannot satisfy on
					its own — it asks what the system does, not what the organisation promises.`,
				`El artículo 25 es la cláusula que más directamente premia las decisiones
					arquitectónicas. Exige que la protección de datos esté diseñada en el sistema
					desde el principio y que, por defecto, solo se traten los datos personales
					necesarios para cada finalidad específica. Es el requisito que una política
					diligente no puede satisfacer por sí sola: pregunta qué hace el sistema, no qué
					promete la organización.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 173, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var26))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var27 string
			templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`In a client-heavy architecture, personal data is routinely copied into the
					browser to render a view: profile records in a state store, transaction lists in
					memory, draft form data in localStorage, cached responses the framework retains
					for performance. Each copy is personal data processed on a device the operator
					does not control, persisting for a lifetime the operator did not choose. Every
					one of those copies is in scope for Article 25, and each is a place minimisation
					can quietly fail.`,
				`En una arquitectura con mucho cliente, los datos personales se copian
					habitualmente en el navegador para renderizar una vista: registros de perfil en
					un almacén de estado, listas de transacciones en memoria, borradores de
					formularios en localStorage, respuestas cacheadas que el framework conserva por
					rendimiento. Cada copia es un dato personal tratado en un dispositivo que el
					responsable no controla y que persiste durante un tiempo que el responsable no
					eligió. Todas esas copias entran en el ámbito del artículo 25, y cada una es un
					punto donde la minimización puede fallar en silencio.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 190, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var27))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var28 string
			templ_7745c5c3_Var28, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Under a server-authoritative model the browser holds no application state. It
					receives a rendered projection — exactly the fields needed for the view in front
					of the user, and nothing more — and discards it on navigation. Minimisation is
					not a discipline applied on top of the data flow; it is the shape of the data
					flow. The server computes the smallest projection that answers the request, and
					that projection is all that ever leaves the trust boundary.`,
				`Bajo un modelo autorizado por el servidor, el navegador no almacena estado de la
					aplicación. Recibe una proyección renderizada —exactamente los campos necesarios
					para la vista que el usuario tiene delante, y nada más— y la descarta al navegar.
					La minimización no es una disciplina aplicada sobre el flujo de datos; es la
					forma del flujo de datos. El servidor calcula la proyección más pequeña que
					responde a la solicitud, y esa proyección es todo lo que llega a cruzar el
					límite de confianza.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 205, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var28))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "</p></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var29 string
			templ_7745c5c3_Var29, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Security of processing — GDPR Article 32 and OWASP", "Seguridad del tratamiento — RGPD artículo 32 y OWASP"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 208, Col: 131}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var29))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var30 string
			templ_7745c5c3_Var30, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Article 32 requires security measures appropriate to the risk, and supervisory
					authorities routinely read it against recognised technical baselines — the OWASP
					Top 10 and the OWASP Application Security Verification Standard chief among them.
					The most consequential category in that list, year after year, is broken access
					control. It is also the one an architecture can eliminate structurally rather
					than defend against case by case.`,
				`El artículo 32 exige medidas de seguridad adecuadas al riesgo, y las autoridades
					de control suelen interpretarlo a la luz de estándares técnicos reconocidos, con
					el OWASP Top 10 y el Estándar de Verificación de Seguridad de Aplicaciones de
					OWASP a la cabeza. La categoría más determinante de esa lista, año tras año, es
					el control de acceso roto. Es también la que una arquitectura puede eliminar de
					forma estructural en lugar de defender caso por caso.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 222, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var30))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var31 string
			templ_7745c5c3_Var31, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`When the client holds state, authorisation becomes a value the client can see and,
					too often, influence — a role flag in a token payload, a hidden field, an object
					identifier in a URL that maps straight to a record. Broken access control is the
					recurring result: the classic client-side privilege escalation, and insecure
					direct object references. When the server is authoritative, none of that state
					exists on the client to tamper with. The server computes what an actor is
					permitted to see and do, on every request, from state the actor never touches.`,
				`Cuando el cliente almacena estado, la autorización se convierte en un valor que
					el cliente puede ver y, con demasiada frecuencia, influir: un indicador de rol en
					el contenido de un token, un campo oculto, un identificador de objeto en una URL
					que apunta directamente a un registro. El control de acceso roto es el resultado
					recurrente: la clásica escalada de privilegios del lado del cliente y las
					referencias directas a objetos inseguras. Cuando el servidor es autoritativo,
					ese estado no existe en el cliente para ser manipulado. El servidor calcula lo
					que un actor puede ver y hacer, en cada solicitud, a partir de un estado que el
					actor nunca toca.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 240, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var31))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var32 string
			templ_7745c5c3_Var32, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				"Mapped against the requirement, the architecture answers several OWASP categories at the structural level rather than the mitigation level:",
				"Frente al requisito, la arquitectura responde a varias categorías de OWASP a nivel estructural en lugar de a nivel de mitigación:",
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 244, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var32))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "</p><ul><li><strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var33 string
			templ_7745c5c3_Var33, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A01 Broken Access Control.", "A01 Control de acceso roto."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 247, Col: 83}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var33))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var34 string
			templ_7745c5c3_Var34, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 248, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var34))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var35 string
			templ_7745c5c3_Var35, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Authorisation is computed server-side per request; there is no client-held permission to escalate.", "La autorización se calcula en el servidor en cada solicitud; no hay un permiso almacenado en el cliente que escalar."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 248, Col: 244}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var35))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</li><li><strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var36 string
			templ_7745c5c3_Var36, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A03 Injection.", "A03 Inyección."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 251, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var36))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var37 string
			templ_7745c5c3_Var37, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 252, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var37))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var38 string
			templ_7745c5c3_Var38, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A single server-side validation path guards every state transition; there is no parallel client validation to drift out of sync. Parameterised queries and auto-escaped templates are the default.", "Un único camino de validación en el servidor protege cada transición de estado; no hay una validación de cliente en paralelo que se desincronice. Las consultas parametrizadas y las plantillas con escape automático son el comportamiento por defecto."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 252, Col: 476}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var38))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</li><li><strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var39 string
			templ_7745c5c3_Var39, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A04 Insecure Design.", "A04 Diseño inseguro."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 255, Col: 71}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var39))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var40 string
			templ_7745c5c3_Var40, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 256, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var40))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var41 string
			templ_7745c5c3_Var41, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("State transitions are validated intents applied against current server truth — the trust boundary is drawn where it can be enforced.", "Las transiciones de estado son intenciones validadas que se aplican contra la verdad actual del servidor: el límite de confianza se traza donde puede imponerse."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 256, Col: 324}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var41))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</li><li><strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var42 string
			templ_7745c5c3_Var42, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A05 Security Misconfiguration.", "A05 Configuración de seguridad incorrecta."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 259, Col: 103}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var42))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var43 string
			templ_7745c5c3_Var43, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 260, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var43))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var44 string
			templ_7745c5c3_Var44, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A minimal dependency surface and no client build pipeline means fewer moving parts to misconfigure or leave exposed.", "Una superficie de dependencias mínima y la ausencia de una cadena de compilación en el cliente significan menos piezas móviles que configurar mal o dejar expuestas."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 260, Col: 312}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var44))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "</li><li><strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var45 string
			templ_7745c5c3_Var45, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("A09 Logging and Monitoring Failures.", "A09 Fallos de registro y monitorización."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 263, Col: 107}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var45))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var46 string
			templ_7745c5c3_Var46, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 264, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var46))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var47 string
			templ_7745c5c3_Var47, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Every state transition passes through one gateway and is logged there once — the audit trail is a by-product, not an add-on.", "Cada transición de estado pasa por una única puerta de enlace y se registra allí una sola vez: el rastro de auditoría es un subproducto, no un añadido."))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 264, Col: 311}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var47))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "</li></ul></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var48 string
			templ_7745c5c3_Var48, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Accountability and the audit trail — Article 5(2), NIS2, DORA", "Responsabilidad proactiva y rastro de auditoría — artículo 5(2), NIS2, DORA"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 269, Col: 166}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var48))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var49 string
			templ_7745c5c3_Var49, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Three separate obligations converge on the same technical need. GDPR Article 5(2)
					requires the controller to be able to demonstrate compliance. NIS2 requires
					incident detection and reporting on a 24-and-72-hour clock. DORA requires the
					reconstruction of what happened to which data. All three assume the system can
					produce a truthful, ordered record of what it did.`,
				`Tres obligaciones distintas convergen en la misma necesidad técnica. El artículo
					5(2) del RGPD exige que el responsable pueda demostrar el cumplimiento. NIS2 exige
					la detección y notificación de incidentes con plazos de 24 y 72 horas. DORA exige
					la reconstrucción de qué ocurrió y sobre qué datos. Las tres presuponen que el
					sistema puede producir un registro veraz y ordenado de lo que hizo.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 281, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var49))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var50 string
			templ_7745c5c3_Var50, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`A server-authoritative system persists state as an append-only event log: every
					transition is an entry, written once, never mutated. That is not a compliance
					feature bolted on to satisfy an auditor — it is how the system stores state in
					the first place. The record required to demonstrate accountability, to file a
					72-hour NIS2 notification with substance, and to satisfy DORA traceability is the
					same log the application already relies on to know what is true.`,
				`Un sistema autorizado por el servidor persiste el estado como un registro de
					eventos de solo anexión: cada transición es una entrada, escrita una vez y nunca
					modificada. Eso no es una funcionalidad de cumplimiento añadida para satisfacer a
					un auditor: es la forma en que el sistema almacena el estado desde el principio.
					El registro necesario para demostrar la responsabilidad, para presentar una
					notificación NIS2 de 72 horas con contenido y para satisfacer la trazabilidad de
					DORA es el mismo registro del que la aplicación ya depende para saber qué es
					verdad.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 297, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var50))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "</p><div class=\"blog-stat-row\"><div class=\"blog-stat blog-stat--exposed\"><span class=\"blog-stat__num\">24h</span> <span class=\"blog-stat__label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var51 string
			templ_7745c5c3_Var51, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("early warning", "alerta temprana"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 301, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var51))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "</span> <span class=\"blog-stat__sublabel\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var52 string
			templ_7745c5c3_Var52, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("NIS2 incident clock", "reloj de incidentes NIS2"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 302, Col: 99}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var52))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</span></div><div class=\"blog-stat blog-stat--exposed\"><span class=\"blog-stat__num\">72h</span> <span class=\"blog-stat__label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var53 string
			templ_7745c5c3_Var53, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("full notification", "notificación completa"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 306, Col: 92}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var53))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "</span> <span class=\"blog-stat__sublabel\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var54 string
			templ_7745c5c3_Var54, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("NIS2 · GDPR breach", "NIS2 · brecha RGPD"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 307, Col: 94}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var54))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, "</span></div><div class=\"blog-stat blog-stat--safe\"><span class=\"blog-stat__num\">1</span> <span class=\"blog-stat__label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var55 string
			templ_7745c5c3_Var55, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("append-only log", "registro de solo anexión"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 311, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var55))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, "</span> <span class=\"blog-stat__sublabel\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var56 string
			templ_7745c5c3_Var56, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("answers all three", "responde a las tres"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 312, Col: 92}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var56))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, "</span></div></div></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var57 string
			templ_7745c5c3_Var57, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Erasure, residency, and the cookie question", "Supresión, residencia y la cuestión de las cookies"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 317, Col: 119}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var57))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var58 string
			templ_7745c5c3_Var58, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The right to erasure under Article 17 is bounded by where the data lives. When
					state exists only server-side, erasure is an operation against known storage the
					operator controls. When copies of personal data are scattered across browser
					caches, local storage, and framework state stores, the operator cannot fully
					honour an erasure request for data sitting on a device it never sees. A single
					authoritative store is not merely tidier — it is the difference between an
					erasure guarantee you can make and one you cannot.`,
				`El derecho de supresión del artículo 17 está limitado por dónde residen los datos.
					Cuando el estado existe solo en el servidor, la supresión es una operación sobre
					un almacenamiento conocido que el responsable controla. Cuando hay copias de
					datos personales dispersas por cachés del navegador, almacenamiento local y
					almacenes de estado del framework, el responsable no puede atender por completo
					una solicitud de supresión sobre datos que residen en un dispositivo que nunca
					ve. Un único almacén autoritativo no es solo más ordenado: es la diferencia entre
					una garantía de supresión que puedes ofrecer y una que no.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 334, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var58))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 52, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var59 string
			templ_7745c5c3_Var59, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Data residency follows the same logic. Keeping personal data on EU-hosted
					infrastructure is undermined the moment the frontend pulls scripts, fonts, or
					data from third-party CDNs at runtime — each such request can carry an IP address
					and referrer to infrastructure outside the operator's control and outside the EU.
					A server-authoritative site renders on infrastructure the operator chooses and
					ships no runtime third-party requests, keeping the data path inside the boundary
					the operator actually declared.`,
				`La residencia de los datos sigue la misma lógica. Mantener los datos personales
					en infraestructura alojada en la UE se socava en el momento en que el frontend
					descarga scripts, fuentes o datos de CDNs de terceros en tiempo de ejecución:
					cada una de esas solicitudes puede transmitir una dirección IP y un referente a
					infraestructura fuera del control del responsable y fuera de la UE. Un sitio
					autorizado por el servidor se renderiza en la infraestructura que el responsable
					elige y no emite solicitudes a terceros en tiempo de ejecución, manteniendo la
					ruta de los datos dentro del límite que el responsable realmente declaró.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 351, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var59))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 53, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var60 string
			templ_7745c5c3_Var60, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The ePrivacy consent requirement is triggered by non-essential reads from and
					writes to the user's device. An architecture that keeps no meaningful state on
					the client has little reason to touch localStorage or set analytics cookies in
					the first place. A single HttpOnly, Secure, SameSite session cookie is strictly
					necessary to deliver the service and falls under the consent exemption. Less
					client-side state means a smaller consent surface — and fewer places a consent
					failure can occur.`,
				`El requisito de consentimiento de la privacidad electrónica se activa por lecturas
					y escrituras no esenciales en el dispositivo del usuario. Una arquitectura que no
					mantiene estado significativo en el cliente tiene pocos motivos para tocar
					localStorage o establecer cookies de analítica en primer lugar. Una única cookie
					de sesión HttpOnly, Secure y SameSite es estrictamente necesaria para prestar el
					servicio y queda cubierta por la exención de consentimiento. Menos estado en el
					cliente significa una menor superficie de consentimiento, y menos lugares donde
					un fallo de consentimiento pueda producirse.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 368, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var60))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 54, "</p><blockquote class=\"callout\"><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var61 string
			templ_7745c5c3_Var61, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`European regulation keeps asking the same underlying question in different
						registers: where does the data live, who can change it, and can you prove what
						happened to it? A server-authoritative architecture gives one answer to all
						three — the server owns the state, mediates every change, and logs it once —
						which is exactly the shape the regulation was written to require.`,
				`La regulación europea plantea la misma pregunta de fondo en registros distintos:
						¿dónde residen los datos, quién puede cambiarlos y puedes demostrar qué les
						ocurrió? Una arquitectura autorizada por el servidor da una única respuesta a
						las tres —el servidor posee el estado, media cada cambio y lo registra una sola
						vez—, que es exactamente la forma que la regulación se escribió para exigir.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 381, Col: 6}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var61))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 55, "</p></blockquote></section><section><h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var62 string
			templ_7745c5c3_Var62, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("What the architecture does not do", "Lo que la arquitectura no hace"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 385, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var62))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 56, "</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var63 string
			templ_7745c5c3_Var63, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`Compliance is organisational before it is technical, and no architecture discharges
					the parts that are genuinely about governance. A server-authoritative system does
					not establish a lawful basis for processing, does not appoint a data protection
					officer, and does not carry out the data protection impact assessment that
					high-risk processing requires. It does not write your records of processing, run
					your resilience tests, or file your incident notifications. It does not encrypt
					data at rest or manage keys for you — Article 32 still expects those, and they
					remain configuration and operational discipline.`,
				`El cumplimiento es organizativo antes que técnico, y ninguna arquitectura libera
					de las partes que son genuinamente de gobernanza. Un sistema autorizado por el
					servidor no establece una base jurídica para el tratamiento, no designa un
					delegado de protección de datos y no realiza la evaluación de impacto que exige
					el tratamiento de alto riesgo. No redacta tus registros de tratamiento, no ejecuta
					tus pruebas de resiliencia ni presenta tus notificaciones de incidentes. No cifra
					los datos en reposo ni gestiona las claves por ti: el artículo 32 sigue
					esperándolo, y eso continúa siendo configuración y disciplina operativa.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 403, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var63))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 57, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var64 string
			templ_7745c5c3_Var64, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`What the architecture does is narrower and worth stating precisely: it removes
					whole classes of requirement from the category of things you must remember to do,
					and moves them into the category of things the system does by construction.
					Minimisation becomes the shape of the data flow. Access control becomes a
					server-side computation with nothing on the client to escalate. The audit trail
					becomes the storage model. Those are not the whole of compliance — but they are
					the parts most likely to fail quietly under a client-heavy architecture, and the
					parts a diligent policy document cannot fix on its own.`,
				`Lo que la arquitectura sí hace es más limitado y merece enunciarse con precisión:
					elimina clases enteras de requisitos de la categoría de cosas que debes recordar
					hacer y las traslada a la categoría de cosas que el sistema hace por construcción.
					La minimización se convierte en la forma del flujo de datos. El control de acceso
					se convierte en un cálculo del servidor sin nada en el cliente que escalar. El
					rastro de auditoría se convierte en el modelo de almacenamiento. Eso no es la
					totalidad del cumplimiento, pero sí las partes con más probabilidad de fallar en
					silencio bajo una arquitectura con mucho cliente, y las partes que un documento
					de políticas diligente no puede arreglar por sí solo.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 422, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var64))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 58, "</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var65 string
			templ_7745c5c3_Var65, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T(
				`The regulatory direction of travel in Europe is settled: security must be
					demonstrable, built in, and on by default. That is a description of an
					architectural property, not a policy aspiration. Choosing where state lives is
					choosing how much of that description your system satisfies before anyone writes
					a word of documentation.`,
				`La dirección regulatoria en Europa está fijada: la seguridad debe ser demostrable,
					incorporada y activada por defecto. Eso describe una propiedad arquitectónica, no
					una aspiración de política. Elegir dónde reside el estado es elegir cuánto de esa
					descripción satisface tu sistema antes de que nadie escriba una sola palabra de
					documentación.`,
			))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 434, Col: 5}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var65))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 59, "</p><p><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var66 templ.SafeURL
			templ_7745c5c3_Var66, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(lang.Prefix() + "/why"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 435, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var66))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 60, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var67 string
			templ_7745c5c3_Var67, templ_7745c5c3_Err = templ.JoinStringErrs(lang.T("Read the full argument", "Leer el argumento completo"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/blog_post_eu_compliance.templ`, Line: 435, Col: 117}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var67))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 61, "</a></p></section></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(
			lang.T("Compliance by architecture: GDPR, NIS2, and the EU security baseline", "Cumplimiento por arquitectura: RGPD, NIS2 y el estándar de seguridad de la UE"),
			lang.T(
				"The EU now regulates web application security through GDPR, NIS2, the Cyber Resilience Act, and DORA. Server-authoritative UI turns several of their requirements from paperwork into structural properties of the system.",
				"La UE ahora regula la seguridad de las aplicaciones web mediante el RGPD, NIS2, la Ley de Ciberresiliencia y DORA. La interfaz autorizada por el servidor convierte varios de sus requisitos, de trámites en propiedades estructurales del sistema.",
			),
			csrfToken,
			lang.Prefix()+"/blog/eu-compliance",
			"/static/css/blog.css",
			lang,
		).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
